[[redirects]]
  from = "/api/*"
  to = "https://skillboostenglish.netlify.app/api/:splat"
  status = 200
  force = true[[redirects]]
  from = "/api/*"
  to = "https://skillboostenglish.netlify.app/api/:splat"
  status = 200
  force = true